@props(['store'])
<footer class="site-footer">
    <div class="container footer-grid">
        <div><a href="{{ route('home') }}"><img class="footer-logo" src="{{ asset('images/figma/7ce94.png') }}" alt="Selva Electricals" width="56" height="56" loading="lazy"></a><p>Jaffna’s wholesale and retail supplier for high-grade electrical installations, safety switchgear, power tools, commercial plumbing, and home improvement hardware.</p><address><a href="#contact"><x-store-icon file="e1f59.svg" :size="16" /> {{ $store['address'] }}</a><a href="tel:{{ $store['phone_link'] }}"><x-store-icon file="9a664.svg" :size="16" /> {{ $store['phone'] }} / {{ $store['whatsapp_display'] }}</a><a href="mailto:{{ $store['email'] }}"><x-store-icon file="02199.svg" :size="16" /> {{ $store['email'] }}</a></address></div>
        <div><h2>Quick Links</h2><nav aria-label="Footer navigation"><a href="{{ route('home') }}#home">Home Storefront</a><a href="{{ route('home') }}#products" data-reset-products>All Products & Supplies</a><a href="{{ route('home') }}#categories">Shop by Category</a><a href="{{ route('home') }}#services">Services & Contractor Support</a><a href="{{ route('about') }}">About Our Store</a><a href="{{ route('home') }}#contact">Store Location & Directions</a></nav></div>
        <div><h2>Product Categories</h2><nav aria-label="Footer product categories"><a href="{{ route('home') }}#products" data-category="electrical,cables,switches">Electrical & Industrial Wiring</a><a href="{{ route('home') }}#products" data-category="lighting">LED & Architectural Lighting</a><a href="{{ route('home') }}#products" data-category="power-tools,hand-tools">Power Drills & Hand Tools</a><a href="{{ route('home') }}#products" data-category="plumbing">Plumbing, PVC Pipes & Valves</a><a href="{{ route('home') }}#products" data-category="hardware">Structural Hardware & Fasteners</a><a href="{{ route('home') }}#products" data-category="paints">Paints, Sealants & Waterproofing</a></nav></div>
        <div><h2>Customer Care & Direct Ordering</h2><p>Need custom lengths of cable, bulk cement orders, or fast project deliveries? Speak to our Jaffna order desk.</p><div class="footer-order"><button class="button button-soft" data-open="quote"><x-store-icon file="72817.svg" :size="16" /> Request Official Project Quotation</button><a class="button button-green" href="https://wa.me/{{ $store['whatsapp'] }}" target="_blank" rel="noopener"><x-store-icon file="49cd5.svg" :size="16" /> WhatsApp Direct Order Desk</a></div><p class="footer-note"><x-store-icon file="d2edd.svg" :size="16" /> Islandwide Freight & Jaffna Counter Pickup</p><p class="footer-note"><x-store-icon file="80796.svg" :size="16" /> Genuine Brand Manufacturer Warranties</p></div>
    </div>
    <div class="footer-bottom"><div class="container"><p>© {{ date('Y') }} Selva Electricals Hardware. All rights reserved. Registered Sri Lankan Business.</p><div class="payment-methods"><small>ACCEPTED MODES:</small><span>Bank Transfer</span><span>Cash on Delivery</span><span>LANKAQR</span><span>Visa / Master</span></div><a class="footer-chat" href="https://wa.me/{{ $store['whatsapp'] }}" target="_blank" rel="noopener" aria-label="Chat on WhatsApp"><x-store-icon file="e16b8.svg" :size="20" /></a></div></div>
</footer>
