<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Electrical supplies, lighting, power tools and plumbing essentials at Selva Electricals Hardware in Thirunelveli, Jaffna. Request a project quotation.">
    <meta name="theme-color" content="#000e22">
    <title>Selva Electricals Hardware | Electrical & Hardware Supplies, Jaffna</title>
    <link rel="icon" href="{{ asset('images/figma/7ce94.png') }}" type="image/png">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <a class="skip-link" href="#main">Skip to content</a>
    <x-navbar :store="$store" />
    <main id="main">
        <section class="hero" aria-labelledby="hero-heading">
            <div class="container hero-grid">
                <div class="hero-copy">
                    <span class="trust-badge"><x-store-icon file="10032.svg" :size="15" /> Trusted Electrical & Hardware Specialists in Sri Lanka</span>
                    <h1 id="hero-heading">Quality Electrical & Hardware<br class="desktop-break"> Products for Every Project</h1>
                    <p>Find reliable electrical fittings, 100% pure copper cables, plumbing essentials, heavy-duty power tools, and home improvement gear from top certified brands at Selva Electricals Hardware.</p>
                    <div class="hero-actions"><a href="#products" class="button button-amber" data-reset-products>Shop Products <x-store-icon file="c9874.svg" :size="16" /></a><button class="button button-white" data-open="quote"><x-store-icon file="228c7.svg" /> Request Quotation</button><a href="https://wa.me/{{ $store['whatsapp'] }}" class="button button-green" target="_blank" rel="noopener"><x-store-icon file="7cef1.svg" /> Chat on WhatsApp</a></div>
                    <div class="hero-metrics"><div><x-store-icon file="0ded3.svg" :size="23" /><span><strong>5,000+</strong><small>SKUs in Stock</small></span></div><div><x-store-icon file="ae332.svg" :size="23" /><span><strong>SLSI Cert.</strong><small>Authorized Dealer</small></span></div><div><x-store-icon file="ccb3a.svg" :size="23" /><span><strong>Islandwide</strong><small>Safe Dispatch</small></span></div></div>
                </div>
                <div class="hero-showcase">
                    <div class="hero-image" data-hero-carousel aria-roledescription="carousel" aria-label="Featured products"><div class="hero-slides"><figure class="hero-slide is-active" data-slide="0" data-caption="Best Sellers: ACL Cables & Orange Electric" data-certification="100% Genuine Certified" data-standard="Full SLSI & CE standards" data-status="IN STOCK"><img class="hero-photo" src="{{ asset('images/figma/a74a3.png') }}" alt="Professional drills, copper cable, switches and plumbing fittings at Selva Electricals" width="848" height="460" fetchpriority="high"></figure><figure class="hero-slide" data-slide="1" data-caption="Contractor Choice: Bosch Professional" data-certification="Professional Grade Tools" data-standard="550W impact drill | 1 Year Warranty" data-status="READY TO SHIP"><img class="hero-photo" src="{{ asset('images/figma/6eec0.png') }}" alt="Bosch professional impact drill" width="848" height="460" loading="lazy"></figure><figure class="hero-slide" data-slide="2" data-caption="Trusted Wiring: ACL Pure Copper" data-certification="100% Electrolytic Copper" data-standard="450/750V | Standard 100m coil" data-status="IN STOCK"><img class="hero-photo" src="{{ asset('images/figma/8664b.png') }}" alt="ACL pure copper cable roll" width="848" height="460" loading="lazy"></figure><figure class="hero-slide" data-slide="3" data-caption="Plumbing Essentials: Quality Fittings" data-certification="Reliable Certified Hardware" data-standard="Built for residential & commercial projects" data-status="AVAILABLE"><img class="hero-photo" src="{{ asset('images/figma/f692a.png') }}" alt="Brass plumbing valves and fittings" width="848" height="460" loading="lazy"></figure></div><span class="showcase-top"><x-store-icon file="b4018.svg" :size="15" /> <span data-carousel-caption>Best Sellers: ACL Cables & Orange Electric</span></span><button class="carousel-arrow carousel-prev" type="button" data-carousel-prev aria-label="Previous featured product">‹</button><button class="carousel-arrow carousel-next" type="button" data-carousel-next aria-label="Next featured product">›</button><div class="carousel-dots" role="tablist" aria-label="Featured product slides"><button class="is-active" type="button" data-carousel-dot="0" role="tab" aria-label="Show slide 1" aria-selected="true"></button><button type="button" data-carousel-dot="1" role="tab" aria-label="Show slide 2" aria-selected="false"></button><button type="button" data-carousel-dot="2" role="tab" aria-label="Show slide 3" aria-selected="false"></button><button type="button" data-carousel-dot="3" role="tab" aria-label="Show slide 4" aria-selected="false"></button></div><div class="showcase-bottom"><span class="certification-icon"><x-store-icon file="870f7.svg" :size="22" /></span><span><strong data-carousel-certification>100% Genuine Certified</strong><small data-carousel-standard>Full SLSI & CE standards</small></span><span class="stock-label" data-carousel-status>IN STOCK</span></div></div>
                    <div class="showcase-specs"><span><x-store-icon file="c1f58.svg" /> Residential & Commercial</span><span><x-store-icon file="3be1b.svg" /> Contractor Grade Tools</span></div>
                </div>
            </div>
        </section>
        <section class="section trust-section" aria-label="Our commitments"><div class="container feature-grid">@foreach ($store['features'] as $feature)<article class="feature-card"><span class="feature-icon"><x-store-icon :file="$feature['icon']" :size="28" /></span><h2>{{ $feature['title'] }}</h2><p>{{ $feature['description'] }}</p><a href="#services">{{ $feature['label'] }} <x-store-icon :file="$feature['small_icon']" :size="16" /></a></article>@endforeach</div></section>
        <section class="section categories-section" id="categories" aria-labelledby="categories-heading">
            <div class="container"><div class="section-heading"><div><p class="eyebrow">Full inventory spectrum</p><h2 id="categories-heading">Shop by Category</h2><p>Everything you need for electrical installations, plumbing networks, contractor power<br class="desktop-break"> equipment, and home improvement.</p></div><a href="#category-grid" class="text-link">View All 10 Categories <x-store-icon file="5bab9.svg" :size="16" /></a></div>
                <div class="category-grid" id="category-grid">@foreach ($store['categories'] as $category)<a class="category-card" href="#products" data-category="{{ $category['id'] }}"><div class="category-image"><img src="{{ asset('images/figma/'.$category['image']) }}" alt="{{ $category['name'] }}" loading="lazy" width="400" height="256"><span>{{ $category['stock'] }} SKUs</span></div><h3>{{ $category['name'] }}</h3><p>{{ $category['description'] }}</p><strong>Explore <x-store-icon file="05f1c.svg" :size="10" /></strong></a>@endforeach</div>
            </div>
        </section>
        <section class="section products-section" id="products" aria-labelledby="products-heading">
            <div class="container"><div class="section-heading"><div><p class="eyebrow">Top verified hardware</p><h2 id="products-heading">Featured Products</h2></div><div class="product-filters" role="group" aria-label="Filter products"><button class="selected" data-filter="all" aria-pressed="true">All Products</button><button data-filter="electrical,cables,switches" aria-pressed="false">Electrical & Wiring</button><button data-filter="lighting" aria-pressed="false">Lighting</button><button data-filter="power-tools" aria-pressed="false">Power Tools</button><button data-filter="plumbing" aria-pressed="false">Plumbing Essentials</button></div></div>
                <div class="search-status" id="search-status" hidden><p role="status" id="results-label"></p><button class="text-link" data-reset-products>Clear filters</button></div>
                <div class="product-grid">@foreach ($store['products'] as $product)<x-product-card :product="$product" :whatsapp="$store['whatsapp']" />@endforeach</div>
                <div class="empty-state" id="no-products" hidden><h3>No featured products match your search.</h3><p>Our counter stocks much more. Send us the item you need and we’ll check availability.</p><button class="button button-navy" data-open="quote">Request an item</button><button class="button button-soft" data-reset-products>Show all products</button></div>
                <div class="catalog-cta"><button class="button button-soft" data-open="catalog">Explore All 5,000+ Hardware Items in Catalog <x-store-icon file="0368e.svg" /></button></div>
            </div>
        </section>
        <section class="section project-section" aria-labelledby="project-heading"><div class="container"><div class="project-banner"><div><span class="project-badge"><x-store-icon file="f7c9f.svg" :size="16" /> Contractors, builders & homeowners</span><h2 id="project-heading">Planning a House Construction or Commercial Renovation?</h2><p>Send us your BOQ (Bill of Quantities) or handwritten hardware item list on WhatsApp. Our electrical engineers and hardware specialists will prepare a competitive, itemized discounted quotation within 2 hours.</p><ul class="project-perks">@foreach (['Special Bulk Contractor Pricing', 'Free Cable Amperage Calculation', 'Jobsite Phased Delivery'] as $perk)<li><x-store-icon file="5b529.svg" :size="15" /> {{ $perk }}</li>@endforeach</ul></div><div class="project-actions"><button class="button button-amber" data-open="quote"><x-store-icon file="48e6b.svg" /> Submit BOQ / Product List</button><a class="button button-green" href="https://wa.me/{{ $store['whatsapp'] }}" target="_blank" rel="noopener"><x-store-icon file="7cef1.svg" /> Direct WhatsApp ({{ $store['whatsapp_display'] }})</a></div></div></div></section>
        <section class="section about-section" id="about" aria-labelledby="about-heading"><div class="container about-grid"><div class="about-collage"><div><img src="{{ asset('images/figma/dcf44.png') }}" alt="Inside the Selva Electricals hardware store" loading="lazy" width="480" height="360"><img src="{{ asset('images/figma/2dbbb.png') }}" alt="Pure copper cable coils" loading="lazy" width="480" height="260"></div><div><img src="{{ asset('images/figma/f692a.png') }}" alt="Brass plumbing valves and pressure gauges" loading="lazy" width="480" height="260"><img src="{{ asset('images/figma/05da3.png') }}" alt="Counter staff assisting a contractor" loading="lazy" width="480" height="360"></div></div><div><p class="eyebrow">Why trade with us</p><h2 id="about-heading">Sri Lanka’s Reliable Hardware & Electrical Partner</h2><p class="about-intro">With decades of combined experience on the counter, Selva Electricals Hardware stands for uncompromised material safety, upfront pricing, and deep technical assistance for builders, technicians, and local homeowners.</p><ul class="benefits">@foreach ($store['benefits'] as $benefit)<li><x-store-icon file="c4d46.svg" :size="20" /><div><h3>{{ $benefit['title'] }}</h3><p>{{ $benefit['description'] }}</p></div></li>@endforeach</ul><a class="button button-navy" href="#contact">Learn More About Our Store <x-store-icon file="b0702.svg" :size="16" /></a></div></div></section>
        <section class="section services-section" id="services" aria-labelledby="services-heading"><div class="container"><div class="center-heading"><p class="eyebrow">Trade capabilities</p><h2 id="services-heading">More Than Just a Hardware Shop</h2><p>Comprehensive project assistance tailored to keep construction sites on time and within budget.</p></div><div class="services-grid">@foreach ($store['services'] as $service)<article class="service-card"><span class="feature-icon"><x-store-icon :file="$service['icon']" :size="24" /></span><h3>{{ $service['title'] }}</h3><p>{{ $service['description'] }}</p><button class="text-link" data-service="{{ $service['title'] }}">Learn More <x-store-icon file="05f1c.svg" :size="10" /></button></article>@endforeach</div></div></section>
        <section class="section testimonials-section" aria-labelledby="reviews-heading"><div class="container"><p class="brand-label">Official authorized retailer for leading trade brands</p><div class="brand-grid">@foreach ([['OR','ORANGE'], ['ACL','ACL CABLES'], ['PH','PHILIPS'], ['BS','BOSCH'], ['SL','S-LON'], ['KV','KEVILTON'], ['ST','STANLEY']] as $brand)<span class="brand-logo"><b>{{ $brand[0] }}</b><strong>{{ $brand[1] }}</strong></span>@endforeach</div><div class="center-heading"><h2 id="reviews-heading">What Our Clients Say</h2><p>Honest feedback from building contractors, electricians, and homeowners.</p></div><div class="reviews-grid">@foreach ($store['reviews'] as $review)<figure class="review-card"><div class="review-stars" aria-label="5 out of 5 stars">@for ($i = 0; $i < 5; $i++)<x-store-icon file="7679a.svg" :size="18" />@endfor</div><blockquote>“{{ $review['quote'] }}”</blockquote><figcaption><span class="avatar">{{ $review['initials'] }}</span><span><strong>{{ $review['name'] }}</strong><small>{{ $review['role'] }}</small></span></figcaption></figure>@endforeach</div></div></section>
        <section class="section contact-section" id="contact" aria-labelledby="contact-heading"><div class="container"><div class="contact-card"><div><span class="location-label"><x-store-icon file="ef89a.svg" :size="14" /> Visit our store in Jaffna</span><h2 id="contact-heading">Need Immediate Supplies Today? Drop by Our Jaffna Counter</h2><p>Visit our store on Palaly Road in Thirunelveli for electrical supplies, hardware essentials, and friendly technical assistance for your next project.</p><div class="contact-details"><span><x-store-icon file="e3dc0.svg" /> {{ $store['address'] }}</span><a href="tel:{{ $store['phone_link'] }}"><x-store-icon file="f6baf.svg" /> {{ $store['phone'] }} / {{ $store['whatsapp_display'] }}</a><span><x-store-icon file="54dd8.svg" /> {{ $store['hours'] }}</span><span><x-store-icon file="fc5fd.svg" /> Immediate Van & Lorry Loading Bay</span></div><div class="contact-actions"><a class="button button-navy" href="https://www.google.com/maps/search/?api=1&query={{ rawurlencode($store['name'].' '.$store['address']) }}" target="_blank" rel="noopener"><x-store-icon file="dfb63.svg" /> Get Driving Directions</a><a class="button button-green" href="https://wa.me/{{ $store['whatsapp'] }}?text={{ rawurlencode('Hello, can you check availability for pickup at your Jaffna counter?') }}" target="_blank" rel="noopener"><x-store-icon file="49cd5.svg" /> Check Counter Stock on WhatsApp</a></div></div><a class="location-map" href="https://www.google.com/maps/search/?api=1&query={{ rawurlencode($store['name'].' '.$store['address']) }}" target="_blank" rel="noopener" aria-label="Open Selva Electricals Jaffna location in Google Maps"><span><x-store-icon file="3d1f0.svg" :size="26" /></span><strong>Selva Electricals Hardware</strong><small>Thirunelveli, Jaffna</small></a></div></div></section>
    </main>
    <x-store-footer :store="$store" />
    <x-store-dialogs :store="$store" />
    <div class="toast" id="store-toast" role="status" aria-live="polite" hidden></div>
    <button class="back-to-top" type="button" id="back-to-top" aria-label="Back to top">↑</button>
    <script type="application/json" id="storefront-data">{!! json_encode(['products' => $store['products'], 'categories' => $store['categories'], 'services' => $store['services'], 'whatsapp' => $store['whatsapp'], 'assetBase' => asset('images/figma')], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
</body>
</html>
