const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  const context = await browser.newContext({viewport: {width: 1440, height: 1000}});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const base = 'http://127.0.0.1:8012';
  await page.goto(base + '/about');
  await page.locator('[data-open="cart"]').click();
  await page.locator('#store-dialog').waitFor({state:'visible'});
  assert.match(await page.locator('#dialog-content').innerText(), /empty/);
  await page.locator('#store-dialog [data-close]').click();
  await page.locator('[data-open="quote"]').first().click();
  await page.locator('#quote-name').fill('Browser test');
  await page.locator('#quote-phone').fill('0777642771');
  await page.locator('#quote-items').fill('Need five bulbs');
  await page.locator('#quotation-form [type="submit"]').click();
  await page.waitForFunction(() => document.querySelector('#quote-result').textContent.includes('received'));
  assert.equal(await page.locator('#quote-whatsapp').isVisible(), true);
  await page.locator('#quote-dialog [data-close]').click();
  await page.locator('#search-query').fill('Philips');
  await page.locator('#product-search [type="submit"]').click();
  await page.waitForURL('**/?category=all&q=Philips#products');
  assert.match(await page.locator('#results-label').innerText(), /Philips/);
  await page.goto(base + '/register');
  await page.locator('#register-first-name').fill('Browser');
  await page.locator('#register-last-name').fill('Account');
  await page.locator('#register-email').fill('browser-' + Date.now() + '@example.com');
  await page.locator('#register-phone').fill('0777642771');
  await page.locator('#register-password').fill('Browser-password-123');
  await page.locator('#register-panel input[type=checkbox]').check();
  await page.locator('#register-panel [type=submit]').click();
  await page.waitForURL(base + '/');
  const saveResponse = page.waitForResponse(r => r.url().endsWith('/account/state') && r.status() === 200);
  await page.locator('[data-add]').first().click();
  await saveResponse;
  await page.reload();
  assert.equal(await page.locator('[data-cart-count]').first().textContent(), '1');
  await page.evaluate(() => window.dispatchEvent(new StorageEvent('storage', {key:'selva-storefront-v1', newValue:JSON.stringify({cart:{},wishlist:[]})})));
  assert.equal(await page.locator('[data-cart-count]').first().textContent(), '1');
  await page.goto(base + '/profile');
  await page.locator('#name').fill('Updated browser');
  await page.locator('#phone').fill('077 123 4567');
  await page.locator('[type=submit]').click();
  await page.locator('[role=status]').waitFor();
  assert.match(await page.locator('[role=status]').innerText(), /updated/);
  await page.goto(base + '/about');
  await page.screenshot({path:path.join(os.tmpdir(), 'selva-desktop.png'), fullPage:false});
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  await page.locator('#mobile-menu-toggle').click();
  assert.equal(await page.locator('#main-navigation').isVisible(),true);
  await page.locator('[data-open=cart]').click();
  await page.locator('#store-dialog').waitFor({state:'visible'});
  assert.match(await page.locator('#dialog-content').innerText(), /Estimated total/);
  await page.locator('#store-dialog [data-close]').click();
  await page.screenshot({path:path.join(os.tmpdir(), 'selva-mobile.png'), fullPage:false});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('PASS: About dialogs, quotation save, search navigation, registration, account cart persistence, guest-event isolation, profile update, mobile menu/cart, no overflow, no JS errors.');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
