<?php

return [
    'name' => 'Selva Electricals',
    'address' => 'No 21, Palaly Road, Thirunelveli, Jaffna.',
    'phone' => '021 221 25955',
    'phone_link' => '02122125955',
    'whatsapp' => '94777642771',
    'whatsapp_display' => '077 764 2771',
    'email' => 'selvahel@gmail.com',
    'hours' => 'Mon - Sat: 8:00 AM – 7:30 PM | Sun: 8:30 AM – 1:30 PM',
    'categories' => [
        [
            'id' => 'electrical',
            'name' => 'Electrical & Distribution',
            'description' => 'MCBs, RCCBs, DB Boxes & Isolators',
            'stock' => '420+',
            'image' => 'f1d06.png',
        ],
        [
            'id' => 'lighting',
            'name' => 'LED & Domestic Lighting',
            'description' => 'Ceiling Panels, Battens, Floodlights',
            'stock' => '680+',
            'image' => '2eefa.png',
        ],
        [
            'id' => 'cables',
            'name' => 'Cables & Wires',
            'description' => 'Single Core, Flexible & Armoured',
            'stock' => '310+',
            'image' => '65cf2.png',
        ],
        [
            'id' => 'switches',
            'name' => 'Switches & Sockets',
            'description' => 'Modular Plates, 13A/15A & Smart',
            'stock' => '540+',
            'image' => '9f226.png',
        ],
        [
            'id' => 'power-tools',
            'name' => 'Power Tools',
            'description' => 'Impact Drills, Grinders & Hammers',
            'stock' => '220+',
            'image' => '154a8.png',
        ],
        [
            'id' => 'hand-tools',
            'name' => 'Hand Tools & Sets',
            'description' => 'Pliers, Spanners, Tapes & Drivers',
            'stock' => '750+',
            'image' => 'd4247.png',
        ],
        [
            'id' => 'plumbing',
            'name' => 'Plumbing & Drainage',
            'description' => 'PVC Pipes, Brass Taps & Valves',
            'stock' => '480+',
            'image' => '5ee6d.png',
        ],
        [
            'id' => 'hardware',
            'name' => 'Hardware & Fasteners',
            'description' => 'SS Screws, Wall Plugs & Locks',
            'stock' => '1,200+',
            'image' => '75461.png',
        ],
        [
            'id' => 'safety',
            'name' => 'Safety Equipment',
            'description' => 'Helmets, Gloves & Protective Gear',
            'stock' => '190+',
            'image' => '06501.png',
        ],
        [
            'id' => 'paints',
            'name' => 'Paints & Chemicals',
            'description' => 'Sealants, Waterproofing & Tapes',
            'stock' => '360+',
            'image' => '1a60b.png',
        ],
    ],
    'products' => [
        [
            'id' => 'philips-led',
            'category' => 'lighting',
            'name' => 'Philips Essential LED Bulb 12W (Cool Daylight - B22)',
            'brand' => 'Philips Lighting',
            'certification' => 'SLSI Approved',
            'specification' => 'Base: B22 | 1200 Lumens | 2 Year Warranty',
            'price' => 850,
            'original_price' => 950,
            'badge' => 'In Stock',
            'image' => 'dc92f.png',
        ],
        [
            'id' => 'orange-socket',
            'category' => 'switches',
            'name' => 'Orange 13A Double Switched Socket Outlet',
            'brand' => 'Orange Electric',
            'certification' => 'Flame Retardant',
            'specification' => '13A 250V | Safety Shutter | 10 Yr Lifetime',
            'price' => 980,
            'original_price' => 1120,
            'badge' => 'Popular Choice',
            'image' => '6da15.png',
        ],
        [
            'id' => 'acl-cable',
            'category' => 'cables',
            'name' => 'ACL 2.5mm Single Core Pure Copper Wire (100m Roll)',
            'brand' => 'ACL Cables',
            'certification' => '100% Electrolytic Cu',
            'specification' => 'Rating: 450/750V | Standard 100m Coil',
            'price' => 10100,
            'original_price' => 10800,
            'badge' => 'In Stock',
            'image' => '8664b.png',
        ],
        [
            'id' => 'bosch-drill',
            'category' => 'power-tools',
            'name' => 'Bosch GSB 550 Professional Impact Drill (13mm Chuck)',
            'brand' => 'Bosch Professional',
            'certification' => '1 Year Warranty',
            'specification' => '550W | 2800 RPM | Masonry / Metal / Wood',
            'price' => 14900,
            'original_price' => 16500,
            'badge' => 'Contractor Choice',
            'image' => '6eec0.png',
        ],
        [
            'id' => 'makita-grinder',
            'category' => 'power-tools',
            'name' => 'Makita 9557HN 4" (100mm) Angle Grinder (840W)',
            'brand' => 'Makita Tools',
            'certification' => 'Heavy Duty',
            'specification' => '840W Motor | 11,000 RPM | Spindle Lock',
            'price' => 18200,
            'original_price' => 19800,
            'badge' => 'In Stock',
            'image' => '8cb8e.png',
        ],
        [
            'id' => 'slon-pipe',
            'category' => 'plumbing',
            'name' => 'S-Lon 1" (32mm) Type 600 uPVC Pressure Pipe (4m Length)',
            'brand' => 'S-Lon Lanka',
            'certification' => 'SLS 147 Certified',
            'specification' => 'Type 600 | Cold Potable Water | 4m Length',
            'price' => 1350,
            'original_price' => 1480,
            'badge' => 'In Stock',
            'image' => 'ea47f.png',
        ],
        [
            'id' => 'kevilton-mcb',
            'category' => 'electrical',
            'name' => 'Kevilton 32A Single Pole MCB Circuit Breaker (6kA)',
            'brand' => 'Kevilton',
            'certification' => 'IEC 60898-1',
            'specification' => 'Curve C | 6kA Breaking Capacity | DIN Rail',
            'price' => 890,
            'original_price' => 990,
            'badge' => 'In Stock',
            'image' => 'e9465.png',
        ],
        [
            'id' => 'stanley-tape',
            'category' => 'hand-tools',
            'name' => 'Stanley PowerLock 8M / 26ft Heavy Duty Measuring Tape',
            'brand' => 'Stanley Hand Tools',
            'certification' => 'Metric / Imperial',
            'specification' => 'Mylar Polyester Film | Tru-Zero Hook',
            'price' => 1650,
            'original_price' => 1850,
            'badge' => 'Best Value',
            'image' => 'b8b41.png',
        ],
    ],
    'features' => [
        [
            'title' => 'Quality Products',
            'description' => 'Reliable genuine products backed by authentic manufacturer guarantees for domestic and industrial projects.',
            'label' => 'Guaranteed Genuine',
            'icon' => '7c096.svg',
            'small_icon' => '41098.svg',
        ],
        [
            'title' => 'Competitive Prices',
            'description' => 'Transparent wholesale and retail price points in Sri Lankan Rupees, ensuring true value on bulk purchases.',
            'label' => 'Wholesale Discounts',
            'icon' => '7c3f4.svg',
            'small_icon' => '57f01.svg',
        ],
        [
            'title' => 'Expert Counter Service',
            'description' => 'Friendly technical guidance to help you choose the right gauge wire, breaker capacity, pump size, and tools.',
            'label' => 'Engineering Advice',
            'icon' => '3d1d1.svg',
            'small_icon' => '077ee.svg',
        ],
        [
            'title' => 'Convenient Delivery',
            'description' => 'Fast catalog inquiries, hassle-free WhatsApp order bookings, and prompt dispatch right to your construction site.',
            'label' => 'Site Delivery',
            'icon' => '6d7d5.svg',
            'small_icon' => '6f3a8.svg',
        ],
    ],
    'services' => [
        [
            'title' => 'Load & Breaker Calculations',
            'description' => 'Free electrical load analysis to select correct MCB amperages and sub-panel wire cross-sections.',
            'icon' => 'd5dac.svg',
        ],
        [
            'title' => 'Plumbing Layout Assistance',
            'description' => 'Assistance sizing overhead water tank inlet pressure lines, pump ratings, and drainage gradients.',
            'icon' => 'fb314.svg',
        ],
        [
            'title' => 'Power Tool Servicing & Guidance',
            'description' => 'Authorized carbon brush replacements, armature testing, drill chuck repairs, and blade advice.',
            'icon' => 'b0f4b.svg',
        ],
        [
            'title' => 'Contractor Bulk Accounts',
            'description' => 'Registered contractor perks including staged site deliveries, monthly invoicing, and BOQ priority.',
            'icon' => '2e8a2.svg',
        ],
        [
            'title' => 'Custom Cable Cutting & Testing',
            'description' => 'Precise meter cuts for 4-core armoured wires, submersible pump flat cords, and megger insulation tests.',
            'icon' => '48bd1.svg',
        ],
    ],
    'benefits' => [
        [
            'title' => 'SLSI & CE Certified Products Guaranteed',
            'description' => 'Zero counterfeit stock. Every cable, breaker, and pipe carries full manufacturer compliance credentials.',
        ],
        [
            'title' => 'Wholesale Tiers for Electricians & Plumbers',
            'description' => 'Special trade account pricing, credit facilities for approved contractors, and bulk volume concessions.',
        ],
        [
            'title' => '5,000+ Ready SKUs in Our Jaffna Store',
            'description' => 'Instant dispatch without waiting for back-orders. If it’s on your requisition list, we keep it in stock.',
        ],
        [
            'title' => 'Expert Counter Engineering Guidance',
            'description' => 'Get the exact breaker rating, cable gauge, and pipe thickness suited to your project.',
        ],
        [
            'title' => 'Local Dispatch & Islandwide Freight',
            'description' => 'Fast delivery to local construction sites and provincial courier partners.',
        ],
    ],
    'reviews' => [
        [
            'initials' => 'RK',
            'name' => 'Rohan Karunaratne',
            'role' => 'General Building Contractor, Colombo',
            'quote' => 'We sourced all the 3-phase switchgear, DB boxes, and 2.5mm ACL wire coils for a 4-storey commercial project in Colombo 03 from Selva Electricals. Their pricing was substantially cheaper than hardware retailers in the suburbs, and their delivery arrived on schedule.',
        ],
        [
            'initials' => 'NM',
            'name' => 'Nimal Munasinghe',
            'role' => 'Homeowner, Nugegoda',
            'quote' => 'I sent a blurry photo of my old broken circuit breaker on their WhatsApp inquiry number. Within 5 minutes, their staff confirmed the exact replacement model, quoted the price, and kept it ready for pickup at the counter. Truly helpful counter service.',
        ],
        [
            'initials' => 'TP',
            'name' => 'Tharindu Perera',
            'role' => 'Certified Domestic Electrician, Dehiwala',
            'quote' => 'Being an electrical technician for 15 years, getting authentic Orange Electric switches with genuine SLSI marks is critical for my reputation. Selva Electricals is a reliable supplier with zero hassle.',
        ],
    ],
];
